sudo: required

language: node_js
node_js:
  - "5"

services:
  - docker

install:
  - cd server/ && npm install && cd ..
  - cd test/ && npm install && cd ..

script:
  - docker build -t dollarshaveclub/fastboot .
  - docker build -t test-container test/fixtures/fastboot-app/.
  - docker run --name fastboot-app -d -e "WORKER_COUNT=1" -p 127.0.0.1:3000:3000 test-container
  - docker ps -a
  - cd test/ && npm test && cd ..

after_script:
  - docker stop fastboot-app
  - docker images -q | xargs docker rmi -f
